.TH "s_tuple" 3 "Mon Jun 27 2016" "C-Tuple" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_tuple \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBt_size\fP"
.br
.RI "\fIThe number of pointers allocated to the t_ptrs array\&. \fP"
.ti -1c
.RI "void ** \fBt_ptrs\fP"
.br
.RI "\fIA collection of generic pointers, each pointer pointing to a value of any type\&. \fP"
.ti -1c
.RI "int * \fBt_stack\fP"
.br
.RI "\fIA collection of flags identifying whether or not a ptr on t_ptrs of the same index has been allocated on the stack\&. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Tuple from the source code\&.
