.TH "s_tuple_part" 3 "Mon Jun 27 2016" "C-Tuple" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_tuple_part \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.RI "\fIA pointer to a value of any type\&. \fP"
.ti -1c
.RI "int \fBon_stack\fP"
.br
.RI "\fIA falg identifying whether or not the value assigned to ptr has been allocated on the stack\&. \fP"
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for C-Tuple from the source code\&.
